# Ackerven
# 2021/11/14 11:40
# config.yaml

# 程序启动时加载数据类型
mode:
  view: Console
  data: excel

# 程序运行环境 Debug or Release
env: Release

DataBase:
  url: localhost
  username: root
  password: 123456

File:
  Debug:
    csv: ../source/default.csv
    excel: ../source/default.xlsx
  Release:
    csv: source/default.csv
    excel: source/default.xlsx

