# Ackerven
# 2021/11/14 11:40
# config.yaml

# 程序启动时加载数据类型
mode:
  view: Console
  data: csv

# 程序运行环境 Debug or Release
env: Debug

DataBase:
  url: localhost
  username: root
  password: 123456

File:
  csv: source/default.csv
  excel: source/default.xlsx

