# Ackerven
# 2021/11/14 11:40
# config.yaml

# 程序启动时加载数据类型
mode:
  view: Console
  data: xlsx

# 程序运行环境 Debug or Release
env: Release

# 数据库连接信息
DataBase:
  url: localhost
  username: root
  password: 123456

# 默认文件路径
File:
  Debug:
    csv: ../source/default.csv
    xlsx: ../source/default.xlsx
  Release:
    csv: source/default.csv
    xlsx: source/default.xlsx

